[package]
name = "quant_features"
version.workspace = true
edition.workspace = true

[dependencies]
quant_data.workspace = true
quant_instruments.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
anyhow.workspace = true
arrow2.workspace = true
ringbuf.workspace = true
tempfile.workspace = true
